// AUTO-GENERATED by scripts/import-feed.mjs — do not edit by hand.
// Source: data/feed.sample.json
// Products: 3
import type { Product } from "@/lib/products";

export const importedProducts: Product[] = [
  {
    "slug": "noise-cancelling-over-ear-headphones-b0example01",
    "name": "Acme Audio Noise Cancelling Over-Ear Headphones",
    "price": 199,
    "compareAt": 249,
    "category": "electronics",
    "images": [
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=900&auto=format&fit=crop"
    ],
    "description": "Over-ear headphones with adaptive noise cancellation and 40 hours of battery life.",
    "details": [
      "Adaptive active noise cancellation",
      "40-hour battery, USB-C fast charge",
      "Bluetooth 5.3 with multipoint pairing"
    ],
    "sizes": [
      "Charcoal",
      "Ivory"
    ],
    "optionLabel": "Color"
  },
  {
    "slug": "linen-blend-relaxed-shirt-b0example02",
    "name": "Northwind Linen Blend Relaxed Shirt",
    "price": 49,
    "compareAt": 69,
    "category": "fashion",
    "images": [
      "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?q=80&w=900&auto=format&fit=crop"
    ],
    "description": "A breathable linen-blend shirt with a relaxed fit and curved hem.",
    "details": [
      "55% linen, 45% cotton",
      "Relaxed fit",
      "Machine wash cold"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "optionLabel": "Size"
  },
  {
    "slug": "solid-oak-coffee-table-b0example03",
    "name": "Fabrikam Solid Oak Coffee Table",
    "price": 329,
    "category": "furniture",
    "images": [
      "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?q=80&w=900&auto=format&fit=crop"
    ],
    "description": "A solid oak coffee table with a hand-rubbed oil finish.",
    "details": [
      "Solid FSC-certified oak",
      "Hand-rubbed oil finish",
      "Assembly in 15 minutes"
    ],
    "sizes": [
      "Natural Oak",
      "Walnut"
    ],
    "optionLabel": "Finish"
  }
];
