#!/usr/bin/env node
/**
 * Imports a licensed product feed into the store catalog.
 *
 *   node scripts/import-feed.mjs data/feed.sample.json
 *
 * Reads a JSON array of FeedItem objects (see lib/feed.ts), validates and
 * normalizes them, then writes lib/products.imported.ts. Import that file in
 * lib/products.ts and concat it with the hand-written catalog.
 *
 * You are responsible for holding the rights to whatever you feed in — an
 * Amazon Associates PA API key, a supplier agreement, or your own photography.
 * Image URLs are referenced as-is, so they must be served from a host whose
 * terms permit it.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

const CATEGORY_MAP = {
  apparel: "fashion", clothing: "fashion", fashion: "fashion", shoes: "fashion",
  electronics: "electronics", computers: "electronics", audio: "electronics", mobiles: "electronics",
  accessories: "accessories", bags: "accessories", watches: "accessories", jewellery: "accessories",
  home: "home", kitchen: "home", decor: "home",
  furniture: "furniture",
  realestate: "realestate", property: "realestate",
  beauty: "beauty", grooming: "beauty",
};

const slugify = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);

const resolveCategory = (raw) => {
  if (!raw) return "home";
  return CATEGORY_MAP[raw.toLowerCase().replace(/[^a-z]/g, "")] ?? "home";
};

function toProduct(item) {
  if (!item.sku || !item.title || !item.images?.length) return null;
  if (!Number.isFinite(item.price) || item.price <= 0) return null;

  const compareAt =
    item.listPrice && item.listPrice > item.price ? item.listPrice : undefined;

  return {
    slug: slugify(`${item.title}-${item.sku}`),
    name: item.brand ? `${item.brand} ${item.title}` : item.title,
    price: Number(item.price.toFixed(2)),
    ...(compareAt ? { compareAt: Number(compareAt.toFixed(2)) } : {}),
    ...(item.inStock === false ? { soldOut: true } : {}),
    category: resolveCategory(item.category),
    images: item.images.filter((u) => /^https?:\/\//.test(u)),
    description: (item.description || item.title).trim(),
    details: item.bullets?.length ? item.bullets : ["See product page for full details"],
    sizes: item.variants?.length ? item.variants : ["One Size"],
    ...(item.variantLabel ? { optionLabel: item.variantLabel } : {}),
  };
}

const source = process.argv[2];
if (!source) {
  console.error("Usage: node scripts/import-feed.mjs <feed.json>");
  process.exit(1);
}

const raw = JSON.parse(readFileSync(resolve(source), "utf8"));
const items = Array.isArray(raw) ? raw : raw.items;
if (!Array.isArray(items)) {
  console.error("Feed must be a JSON array, or an object with an `items` array.");
  process.exit(1);
}

const seen = new Set();
const products = [];
let skipped = 0;

for (const item of items) {
  const p = toProduct(item);
  if (!p) { skipped++; continue; }
  if (seen.has(p.slug)) { skipped++; continue; }
  seen.add(p.slug);
  products.push(p);
}

const out = `// AUTO-GENERATED by scripts/import-feed.mjs — do not edit by hand.
// Source: ${source}
// Products: ${products.length}
import type { Product } from "@/lib/products";

export const importedProducts: Product[] = ${JSON.stringify(products, null, 2)};
`;

const target = resolve("lib/products.imported.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out);

console.log(`Imported ${products.length} products -> lib/products.imported.ts`);
if (skipped) console.log(`Skipped ${skipped} invalid or duplicate rows.`);
const byCat = products.reduce((a, p) => ((a[p.category] = (a[p.category] || 0) + 1), a), {});
console.log("By category:", byCat);
